#!/bin/sh
BASE_DIR=$(dirname $(dirname $0))
JSPM_PATH=$(which jspm 2>/dev/null)
if [ "$?" != "0" ] || [ -z "$JSPM_PATH" ]; then
  echo "jspm not found, make sure it is installed."
  exit 1
fi
JSPM_DIR=$(dirname $(dirname $(readlink $JSPM_PATH || $JSPM_PATH)))
case $JSPM_DIR in /*) ;; *)
  JSPM_DIR="$(dirname $JSPM_PATH)/$JSPM_DIR"
esac
JSPM_LOADER=$JSPM_DIR/node_modules/@jspm/resolve/loader.mjs
if [ ! -f $JSPM_LOADER ]; then
  echo "jspm loader not found, make sure it is installed."
  exit 1
fi
case "$(uname -s)" in
  CYGWIN*|MINGW32*|MINGW64*)
    JSPM_LOADER=/$(cygpath -w "$JSPM_LOADER")
    BASE_DIR=/$(cygpath -w "$BASE_DIR")
    ;;
  *)
esac
NODE_OPTIONS="--experimental-modules --no-warnings --loader $JSPM_LOADER" node "$BASE_DIR/npm\jest@26.6.1\bin/jest.js" "$@"
ret=$?
exit $ret
